name: "Mark and close stale bug issues"

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark and close stale bug issues
        uses: actions/github-script@v7
        with:
          script: |
            const daysBeforeStale = 1;  // Number of days to consider an issue stale
            const staleLabel = 'stale';  // Label to apply to stale issues
            const targetLabel = 'bug';  // Only target issues with this label
            const excludeLabel = 'tracked';  // Exclude issues with this label
            const specificUser = 'alloydsa';  // The specific user who must have commented

            const issues = await github.paginate(github.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: targetLabel,
              per_page: 100,
            });

            const now = new Date();

            for (const issue of issues) {
              // Check if the issue has the exclude label
              if (issue.labels.some(label => label.name === excludeLabel)) {
                continue;
              }

              // Check if the specific user has commented
              const comments = await github.paginate(github.issues.listComments, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
              });

              const userCommented = comments.some(comment => comment.user.login === specificUser);

              if (!userCommented) {
                continue;
              }

              const lastUpdated = new Date(issue.updated_at);
              const daysSinceUpdate = (now - lastUpdated) / (1000 * 60 * 60 * 24);

              if (daysSinceUpdate > daysBeforeStale) {
                // Mark the issue as stale
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: [staleLabel],
                });

                // Post a stale warning comment
                await github.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: "This issue has been automatically marked as stale due to inactivity. If no further activity occurs, it will be closed."
                });
              }
            }
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Close stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity. If no further activity occurs, it will be closed."
          close-issue-message: "This issue has been closed due to inactivity."
          days-before-stale: 1
          days-before-close: 1
          stale-issue-label: "stale"
          exempt-issue-labels: "tracked"
          only-labels: "bug"
          operations-per-run: 30

